spring:
  datasource:    url: jdbc:postgresql://localhost:5432/ProTechCorp
    username: postgres

<<<<<<< HEAD
    password: admin
=======
    password: Comando97
>>>>>>> Eduardo


    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true 