spring:
  datasource:    url: jdbc:postgresql://localhost:5432/ProTechCorp
    username: postgres

<<<<<<< HEAD
    password: admin
=======
    password: Comando97
>>>>>>> 989f937e388d9f1b1fda28e0e0c7a7b77f330588


    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true 